[package]
name = "journal_sql"
edition = "2021"
version.workspace = true

[dependencies]
jira_lib = { path="../jira_lib" }
worklog_lib = {path = "../core" }
anyhow = { workspace = true}
thiserror = {workspace = true}
chrono = { workspace = true}
rusqlite = { version = "0", features = ["bundled"] }