[package]
name = "journal_sql"
edition = "2021"
version.workspace = true

[dependencies]
common = {path = "../common" }
anyhow = { workspace = true}
thiserror = {workspace = true}
chrono = { workspace = true}
rusqlite = { version = "0", features = ["bundled", "chrono"] }