variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/559/packages"

build:win64-msvc:
  stage: build
  image: $CI_REGISTRY/autostore/ci/rust-msvc:240909
  tags:
    - docker-windows-2022
  script:
    - $env:RUSTFLAGS="-Ctarget-feature=+crt-static"
    - cargo build --release
    - Get-ChildItem target/release
    - mv target/release/jira_worklog* .
  artifacts:
    paths:
      - jira_worklog.exe
    expire_in: 14 days

deploy:win64-msvc:
  stage: deploy
  image: alpine:latest
  tags:
    - linux-docker
  dependencies:
    - build:win64-msvc
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - apk add curl
    - >
      curl
      --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
      --upload-file ./jira_worklog.exe
      "${PACKAGE_REGISTRY_URL}/generic/jira_worklog/${CI_COMMIT_TAG:1}/jira_worklog.exe"
