workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
      - ./**/**.md
      - .editorconfig
      - .gitignore
      when: never

build-rust-app:linux:
  stage: build
  image: rust:1.73-alpine3.18
  tags:
    - linux-docker
  script:
    - >
    - cargo build --release
    - cargo test --release
