[package]
name = "timesheet-cli"
description = "Add, delete and get statistics about Jira worklog entries"
readme = "README.md"
authors= ["Steinar Overbeck Cook <steinar.cook@gmail.com>"]
version.workspace = true
edition = "2021"

[[bin]]
name = "timesheet"
path = "src/main.rs"

[dependencies]
worklog-config = { path = "../worklog-config" }
worklog-core = { path = "../worklog-core" }
worklog-jira-adapter = { path = "../worklog-jira-adapter" }
worklog-sqlite-storage = { path = "../worklog-sqlite-storage" }

clap = { version = "4.5.39", features = ["derive"] }

chrono = { workspace = true, features = ["serde"] }
regex = "1"

log = {workspace = true}
env_logger = {  workspace = true }

tokio = { workspace = true, features = ["full"] }
