[package]
name = "journal"
edition = "2021"
version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = {workspace = true}
csv = "1.3"
chrono = {workspace = true}
rand = "0.8"
