//! Sync domain types for Git-like bidirectional sync
//!
//! This module defines types for three-way sync operations:
//! - Fetch: Download from remote without modifying local
//! - Compare: Detect sync states and conflicts
//! - Merge: Auto-apply non-conflicting changes
//! - Push: Upload local changes to remote

use crate::domain::WorklogEntry;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Sync state of a worklog entry (local vs remote)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SyncState {
    /// Local and remote are identical (no action needed)
    InSync,

    /// Entry exists only locally (needs upload to remote)
    LocalOnly,

    /// Entry exists only on remote (needs download to local)
    RemoteOnly,

    /// Entry modified locally since last sync (needs upload)
    LocalNewer,

    /// Entry modified on remote since last sync (needs download)
    RemoteNewer,

    /// Entry modified in both places (needs user resolution)
    Conflict,

    /// Entry deleted locally but still exists on remote (needs remote delete)
    DeletedLocal,

    /// Entry deleted on remote but still exists locally (needs local delete)
    DeletedRemote,
}

impl SyncState {
    /// Check if this state requires user intervention
    #[must_use]
    pub fn needs_user_resolution(&self) -> bool {
        matches!(self, Self::Conflict)
    }

    /// Check if this state can be auto-merged
    #[must_use]
    pub fn can_auto_merge(&self) -> bool {
        !self.needs_user_resolution()
    }
}

/// A sync conflict between local and remote entries
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncConflict {
    /// The provider worklog ID (Jira ID) - primary key for comparison
    pub provider_worklog_id: String,

    /// Local entry (if it exists)
    pub local: Option<WorklogEntry>,

    /// Remote entry (if it exists)
    pub remote: Option<RemoteWorklog>,

    /// The sync state detected
    pub state: SyncState,
}

/// Remote worklog representation (from issue tracker)
///
/// This is similar to `WorklogEntry` but represents the remote state
/// without local metadata like `deleted_at` or local `id`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemoteWorklog {
    /// Remote provider's ID (e.g., Jira worklog ID)
    pub provider_worklog_id: String,

    /// Issue key
    pub issue_key: String,

    /// When work started
    pub started_at: DateTime<Utc>,

    /// When work stopped
    pub stopped_at: DateTime<Utc>,

    /// Time spent in seconds
    pub time_spent_seconds: i32,

    /// Optional comment
    pub comment: Option<String>,

    /// When this was last updated on remote (for conflict detection)
    pub updated_at: DateTime<Utc>,
}

impl RemoteWorklog {
    /// Convert to a local `WorklogEntry`
    ///
    /// Sets sensible defaults for local-only fields:
    /// - `id`: None (will be generated by repository)
    /// - `synced_to_provider`: true (it's from the provider)
    /// - `last_synced_at`: now (just fetched)
    /// - `version`: 1 (fresh from remote)
    /// - `deleted_at`: None (not deleted)
    #[must_use]
    pub fn to_worklog_entry(&self) -> WorklogEntry {
        use chrono::Local;

        let now = Local::now();
        WorklogEntry {
            id: None, // Will be assigned by repository
            issue_key: Some(self.issue_key.clone()),
            started_at: self.started_at.with_timezone(&Local),
            stopped_at: Some(self.stopped_at.with_timezone(&Local)),
            comment: self.comment.clone(),
            tags: vec![],
            time_spent_seconds: Some(self.time_spent_seconds),
            synced_to_provider: true,
            provider_worklog_id: Some(self.provider_worklog_id.clone()),
            created_at: now,
            updated_at: self.updated_at.with_timezone(&Local),
            deleted_at: None,
            last_synced_at: Some(now),
            version: 1,
            has_conflict: false,
        }
    }
}

/// Result of a sync operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncResult {
    /// Number of entries added from remote
    pub added: usize,

    /// Number of entries updated from remote
    pub updated: usize,

    /// Number of entries uploaded to remote
    pub uploaded: usize,

    /// Number of entries deleted locally
    pub deleted_local: usize,

    /// Number of entries deleted on remote
    pub deleted_remote: usize,

    /// Number of conflicts that need user resolution
    pub conflicts: usize,

    /// Detailed list of conflicts (if any)
    pub conflict_details: Vec<SyncConflict>,
}

impl SyncResult {
    /// Create a new empty sync result
    #[must_use]
    pub fn new() -> Self {
        Self {
            added: 0,
            updated: 0,
            uploaded: 0,
            deleted_local: 0,
            deleted_remote: 0,
            conflicts: 0,
            conflict_details: Vec::new(),
        }
    }

    /// Check if any changes were made
    #[must_use]
    pub fn has_changes(&self) -> bool {
        self.added > 0
            || self.updated > 0
            || self.uploaded > 0
            || self.deleted_local > 0
            || self.deleted_remote > 0
    }

    /// Check if there are conflicts
    #[must_use]
    pub fn has_conflicts(&self) -> bool {
        self.conflicts > 0
    }

    /// Total number of operations performed
    #[must_use]
    pub fn total_operations(&self) -> usize {
        self.added + self.updated + self.uploaded + self.deleted_local + self.deleted_remote
    }
}

impl Default for SyncResult {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sync_state_needs_resolution() {
        assert!(SyncState::Conflict.needs_user_resolution());
        assert!(!SyncState::InSync.needs_user_resolution());
        assert!(!SyncState::LocalOnly.needs_user_resolution());
    }

    #[test]
    fn test_sync_state_can_auto_merge() {
        assert!(!SyncState::Conflict.can_auto_merge());
        assert!(SyncState::InSync.can_auto_merge());
        assert!(SyncState::LocalOnly.can_auto_merge());
        assert!(SyncState::RemoteOnly.can_auto_merge());
    }

    #[test]
    fn test_sync_result_new() {
        let result = SyncResult::new();
        assert_eq!(result.added, 0);
        assert_eq!(result.conflicts, 0);
        assert!(!result.has_changes());
        assert!(!result.has_conflicts());
    }

    #[test]
    fn test_sync_result_has_changes() {
        let mut result = SyncResult::new();
        assert!(!result.has_changes());

        result.added = 1;
        assert!(result.has_changes());
    }

    #[test]
    fn test_remote_worklog_to_entry() {
        use chrono::Utc;

        let remote = RemoteWorklog {
            provider_worklog_id: "jira-123".to_string(),
            issue_key: "TEST-1".to_string(),
            started_at: Utc::now(),
            stopped_at: Utc::now(),
            time_spent_seconds: 3600,
            comment: Some("Test work".to_string()),
            updated_at: Utc::now(),
        };

        let entry = remote.to_worklog_entry();
        assert_eq!(entry.provider_worklog_id, Some("jira-123".to_string()));
        assert_eq!(entry.issue_key, Some("TEST-1".to_string()));
        assert!(entry.synced_to_provider);
        assert!(entry.last_synced_at.is_some());
        assert_eq!(entry.version, 1);
        assert!(entry.deleted_at.is_none());
    }
}
