-- set time zone 'CET';
-- show timezone;
create schema if not exists jira;
drop table if exists jira.worklog;
drop table if exists jira.issue;
drop table if exists jira.author;
drop table if exists jira.asset;

create table jira.asset (
    id int primary key generated by default as identity,
    asset_name varchar(255),
    constraint unique_asset_name unique(asset_name)
);

create table jira.project
(
    id   varchar(16) primary key,
    key  varchar(16),
    name varchar(128),
    url  varchar(1024),
    asset_id integer references asset(id),
    foreign key (asset_id) references jira.asset(id)
);


create table jira.issue
(
    id         varchar(16) primary key,
    key        varchar(16),
    project_id varchar(16) references jira.project (id)
);

create table jira.author
(
    id            varchar(64) primary key,
    account_id    varchar(64)
        CONSTRAINT unique_account_id UNIQUE,
    email_address varchar(255),
    display_name  varchar(255)
);

create table jira.worklog
(
    id               varchar(32) primary key,
    account_id       varchar(64) references jira.author (account_id) on delete cascade,
    created          timestamp with time zone,
    updated          timestamp with time zone,
    started          timestamp with time zone,
    timeSpent        varchar(16),
    timeSpentSeconds integer,
    issueId          varchar(32) references jira.issue (id) on delete cascade
);
